set (DEFAULT_MPI_ROOT /Users/dekelsch/brew-4.1.24/)
set (DEFAULT_PARMETIS_ROOT /Users/dekelsch/Software/parmetis-install)
set (DEFAULT_METIS_ROOT /Users/dekelsch/Software/metis-install)
set (DEFAULT_BOOST_ROOT /Users/dekelsch/Software/boost_1_83_0/boost-install)
set (DEFAULT_XML_ROOT /Users/dekelsch/Software/tinyxml)

set (VTK_DIR /Users/dekelsch/Software/VTK-9.3.0/build/lib/cmake/vtk-9.3)
#set (DEFAULT_HDF5_ROOT /Users/dekelsch/Software/hdf5-1.14.2/install)
#set (DEFAULT_HDF5_ROOT /Users/dekelsch/Software/hdf5-1.14.3/build)
#set (DEFAULT_MMG_ROOT )
#set (DEFAULT_PARMMG_ROOT )
