set (DEFAULT_PARALLEL_MPI ON)
set (DEFAULT_PARMETIS_ROOT /Users/dekelsch/Software/parmetis-4.0.3/install)
set (DEFAULT_HDF5_ROOT /Users/dekelsch/Software/hdf5-1.14.2/install)
set (DEFAULT_METIS_ROOT /Users/dekelsch/Software/parmetis-4.0.3/metis/install)
set (DEFAULT_MPI_ROOT /Users/dekelsch/Software/mpich-4.1.2/mpich-4.1.2-install)
#set (DEFAULT_CGNS_ROOT /Users/dekelsch/Software/CGNS-3.3.0/src/install)
set (DEFAULT_VTK_ROOT /Users/dekelsch/Software/VTK-9.3.0.rc1/build)
#set (DEFAULT_PARMMG_ROOT = /Users/dekelsch/Software/parmmg_0805/build)
#set (DEFAULT_MMG_ROOT = /Users/dekelsch/Software/mmg_0805/build)
set (DEFAULT_MMG_ROOT /Users/dekelsch/Software/pmmg/build/Mmg-prefix/src/Mmg-build)
set (DEFAULT_PARMMG_ROOT /Users/dekelsch/Software/pmmg/build)
set (DEFAULT_BOOST_ROOT /Users/dekelsch/Software/boost_1_83_0)
set (DEFAULT_XML_ROOT /Users/dekelsch/Software/tinyxml)
set(Boost_INCLUDE_DIR /Users/dekelsch/Software/boost_1_83_0)
set(Boost_LIBRARY_DIR /Users/dekelsch/Software/boost_1_83_0/stage/lib)
set(VTK_DIR /Users/dekelsch/Software/VTK-9.3.0.rc1/build/lib/cmake/vtk-9.3)
