set (DEFAULT_PARALLEL_MPI ON)
set (DEFAULT_PARMETIS_ROOT /nobackupp19/dekelsch/parmetis-4.0.3/parmetis-install)
set (DEFAULT_HDF5_ROOT /nasa/hdf5/1.8.18_mpt)
set (DEFAULT_METIS_ROOT /nobackupp19/dekelsch/parmetis-4.0.3/metis/metis-install)
set (DEFAULT_MPI_ROOT /nasa/hpe/mpt/2.28_25Apr23_rhel87)
#set (DEFAULT_CGNS_ROOT /Users/dekelsch/Software/CGNS-3.3.0/src/install)
#set (DEFAULT_VTK_ROOT /Users/dekelsch/Software/VTK-9.3.0.rc1/build)
set (DEFAULT_VTK_ROOT /nasa/pkgsrc/toss4/2023Q3)
#set (DEFAULT_PARMMG_ROOT = /Users/dekelsch/Software/parmmg_0805/build)
#set (DEFAULT_MMG_ROOT = /Users/dekelsch/Software/mmg_0805/build)
set (DEFAULT_MMG_ROOT /nobackupp19/dekelsch/Software/ParMmg/build/Mmg-prefix/src/Mmg-build)
set (DEFAULT_PARMMG_ROOT /nobackupp19/dekelsch/Software/ParMmg/build)
set (DEFAULT_BOOST_ROOT /nobackupp19/dekelsch/boost_1_81_0)
set (DEFAULT_XML_ROOT /home1/dekelsch/Software/tinyxml)
set(Boost_INCLUDE_DIR /nobackupp19/dekelsch/boost_1_81_0/boost-install/include)
set(Boost_LIBRARY_DIR /nobackupp19/dekelsch/boost_1_81_0/boost-install/lib)
set(VTK_DIR /nobackupp19/dekelsch/VTK-9.3.0.rc1/build/lib64/cmake/vtk-9.3)
set(VTK_DIR /nasa/pkgsrc/toss4/2023Q3/lib/cmake/vtk-9.2)
set(DEFAULT_EGADS_ROOT /nobackupp19/dekelsch/Software/EngSketchPad)
set(DEFAULT_OPENCASCADE_ROOT /nobackupp19/dekelsch/Software/OCCT-7_8_1/install) 
