#include "adapt.h"
#include "adapt_repartition.h"
#include "adapt_compute.h"
#include "adapt_geometry.h"
#include "adapt_operations.h"
#include "adapt_output.h"

void WritePrismsUS3DFormat(MPI_Comm comm, 
                            RepartitionObject* prism_repart,
                            std::map<int,int> tracetagV2globalV,
                            std::vector<int> &ifn_P,
                            std::map<int,std::vector<int> > ranges_id);


void WritePrismsUS3DFormat_V2(MPI_Comm comm, 
                           std::map<int,std::vector<int> > InternalFaces_P,
                           std::map<int,std::vector<int> > SharedFaces_P,
                           std::map<int, std::vector<double> > LocalVertsMap_P,
                           std::map<int,int> SharedVertsNotOwned,
                           std::map<int,int> NonSharedVertsOwned,
                           std::map<int,int> SharedVertsOwned,
                           std::map<int,std::vector<int> > ElementTag2VertexTag_P,
                           std::map<int,int>  lh_P,
                           std::map<int,int>  rh_P,
                           std::map<int,int> gE2tagE_P,
                           std::map<int,int> NonSharedVertsOwned_P,
                           std::map<int,int> SharedVertsOwned_P,
                           std::set<int> loc_trace_verts,
                           std::map<int,int> tracerefV2globalV,
                           std::vector<int> &ifn_P,
                           std::map<int,std::vector<int> > ranges_id);

void WriteBoundaryDataUS3DFormat(MPI_Comm comm, 
                                RepartitionObject* prism_repart,
                                std::vector<int> ifn_T,
                                std::vector<int> ifn_P,
                                std::map<int,std::vector<int> > bcref2bcface_T,
                                std::map<int,int> tracetagV2globalV,
                                std::map<int,std::vector<int> > BoundaryFaces_T,
                                std::map<int,int> glob2locVid_T,
                                std::vector<std::vector<int> > new_tetrahedra_T,
                                std::vector<double> new_vertices_T,
                                std::map<int,int> LocationSharedVert_T,
                                std::map<int,int> oldglob2newglob_T,
                                std::map<int,int> lh_T_bc,
                                std::map<int,int> new_locE2globE_T,
                                std::vector<std::vector<int> > &bcArrays,
                                std::map<int,int> &bcsizing,
                                std::vector<std::vector<int> > zdefs,
                                std::map<int,int> zone2bcref,
                                std::map<int,char*> zone2name,
                                std::vector<std::vector<char> > znames,
                                std::vector<int> &bciTot_offsets,
                                int &nTotBCFaces,
                                std::set<int> &bcsToT,
                                std::vector<int> &nlbc,
                                std::vector<int> &bci,
                                std::vector<int> &,
                                std::vector<int> &zdefs_new);

void WriteBoundaryDataUS3DFormat_V2(MPI_Comm comm, 
                                std::map<int,std::vector<int> > BoundaryFaces_P,
                                std::map<int, std::vector<double> > LocalVertsMap_P,
                                std::map<int,int> SharedVertsNotOwned_P,
                                std::map<int,int> gE2tagE_P,
                                std::map<int,int>  lh_P,
                                std::map<int,int>  rh_P,
                                std::map<int,std::vector<int> > ElementTag2VertexTag_P,
                                std::map<int,int> NonSharedVertsOwned_P,
                                std::map<int,int> SharedVertsOwned_P,
                                std::set<int> loc_trace_verts,
                                std::map<int,std::vector<int> > bcref2bcface_P,
                                int nLocPrismElem,
                                std::vector<int> ifn_T,
                                std::vector<int> ifn_P,
                                std::map<int,std::vector<int> > bcref2bcface_T,
                                std::map<int,int> tracerefV2globalV,
                                std::map<int,std::vector<int> > BoundaryFaces_T,
                                std::map<int,int> glob2locVid_T,
                                std::vector<std::vector<int> > new_tetrahedra_T,
                                std::vector<double> new_vertices_T,
                                std::map<int,int> LocationSharedVert_T,
                                std::map<int,int> oldglob2newglob_T,
                                std::map<int,int> lh_T_bc,
                                std::map<int,int> new_globE2locE_T,
                                std::vector<std::vector<int> > &bcArrays,
                                std::map<int,int> &bcsizing,
                                std::vector<std::vector<int> > zdefs,
                                std::map<int,int> zone2bcref,
                                std::map<int,char*> zone2name,
                                std::vector<std::vector<char> > znames,
                                std::vector<int> &bciTot_offsets,
                                int &nTotBCFaces,
                                std::set<int> &bcsToT,
                                std::vector<int> &nlbc,
                                std::vector<int> &bcid,
                                std::vector<int> &bci_offsets,
                                std::vector<int> &zdefs_new);